### PR TITLE
Elk5

### LINKED ISSUE #50: Support for ELK 5
At Allstate we been using Logsearch on version 204. We been working in upgrading the Logstash stack to support V5.

We decided to take on this work because we want some filters updated such as the throttle filter which in logstash v5 supports multi threading.

Here are some of the things to notice:

* We are removing default RELP support as it is now provided.
* v2 -> V5 requires a [full restart](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html)  of the Elasticsearch cluster.
* It requires a refactor and compatible release of logsearch-for-cloudfoundry as some of the filter's syntax is changes in logstash v5. (We would take care of this work too)

the PR is almost prepared. We were wondering how this would affect other Logsearch users and if this would be something other users would be intrested in.

@jmcarp @axelaris @Infra-Red

### PR DESCRIPTION
**Pull request by Isaacjcollier**
Fixes #50 

Missing Blob:
- kibana/kibana-5.0.0-linux-x86_64.tar.gz
https://artifacts.elastic.co/downloads/kibana/kibana-5.0.0-linux-x86_64.tar.gz

- logstash/logstash-5.2.2.tar.gz
https://artifacts.elastic.co/downloads/logstash/logstash-5.0.0.tar.gz

- logstash/logstash-filter-alter-3.0.0.zip
zipped https://rubygems.org/downloads/logstash-filter-alter-3.0.0.gem

- logstash/logstash-filter-translate-3.0.1.zip
zipped https://rubygems.org/downloads/logstash-filter-translate-3.0.1.gem

- elasticsearch/elasticsearch-5.0.0.tar.gz
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.tar.gz

### CODE REVIEW

**Comment by bonzofenix** [comment]
We are working on refactoring and fixing the test suite for the logsearch-config project

**Comment by axelaris** [comment]
Hi @Isaacjcollier,
to be clear. Since upgrade v2 -> v5 requires full cluster restart and rolling updates are not supported - this PR is not supposed to be used for running clusters? It only have to be used to deploy a new cluster?

**Comment by bonzofenix** [comment]
@axelaris I think you are right, tomorrow we will start merging a dev release of this branch in lower environments and we will know if it is possible to do rolling upgrades or not. I would still merge this code because eventually we need to upgrade ELK. Can take a look at the PR? we pair on all this changes but I think someone else from the community should review it too before merging! Thank you.

**Comment by bonzofenix** [comment]
@axelaris we found minor bugs related to missing plugins (alter and translate). We are working in adding them as a package. We will be pushing some commits soon.

**Comment by axelaris** [comment]
Thanks, @bonzofenix.
JFYI: I've tried to deploy a fresh ELK5 cluster using this PR. The deployment was unsuccessful, because `elasticsearch` job was failed to start. Here is the error from `elasticsearch.stdout.log`:
```
ERROR: bootstrap checks failed
memory locking requested for elasticsearch process but memory is not locked
```

**Comment by bonzofenix** [comment]
@axelaris thanks for your feedback. Today we started integrating this release and l4cf in our lower environments such as lab and sandbox, all development was done and tested in bosh-lite. We found the same problem. We are working on fixing it, will let you know once we fix it so you can give it another try. Thank you.

**Comment by bonzofenix** [comment]
@axelaris I think it is fixed now can you try again?

**Review by Infra-Red — APPROVED** [review]
:shipit:

**Comment by Infra-Red** [comment]
Everything looks fine after latest commit. I'll merge the PR.

**Pull request merged**
