### PR TITLE
Adding ingestor inputs routing

### PR DESCRIPTION
**Pull request by hjaffan**
Currently release supports adding plugins to the syslog_ingestor, but the problem there is that we are not able to route them from the HAProxy.

This PR allows for an opinionated but also dynamic addition of inputs and HA Proxy configuration.

### CODE REVIEW

**Comment by Infra-Red** [comment]
Hi there! Thank you for submitting the PR. I will take a look at the changes and provide a feedback in coming days.

**Comment by Infra-Red** [comment]
@hjaffan One note, for any agents that are deployed as a bosh-release you can do a simple trick with bosh-dns an avoid using ls-router job. You can configure your job (for example syslog-release) to use `q-s0.ingestor.<NETWORK-NAME>.<DEPLOYMENT-NAME>.bosh` bosh-dns name as a remote address and it's should be enough to spread the load between ingestor instances.

**Comment by hjaffan** [comment]
HI @Infra-Red, So regarding the DNS name, I feel yes that would work, but how would I handled the port routing?

I feel like I had to modify the syslog section here, because the listening ports on the agents / inputs changes

**Comment by Infra-Red** [comment]
Hi @hjaffan. The input port is static across all Logstash instances, for example default port for tcp-input-plugin is 5514. Can you describe your usecase and why port routing required in your setup.

**Comment by hjaffan** [comment]
Hi @Infra-Red , so if you notice, I was exporting the inputs section, now those inputs listen on different ports. 
For example, the main reason for starting this PR was to actually ingest messages coming from beat agents. and those you have to set them up as a different input in the logstash.conf where you put the inputs {} filters {} outputs {}

**Comment by hjaffan** [comment]
@Infra-Red did you have more questions regarding this?

**Review by Infra-Red — CHANGES_REQUESTED** [review]
@hjaffan Sorry that it took so long. Can you rename ops file to `add-beats-input-to-ingestor.yml`, it seems that you made a typo in filename. Overall looks good and I'm fine with merging this change.

**Comment by hjaffan** [comment]
Thanks @Infra-Red  I have updated the name of the file.

**Review by Infra-Red — APPROVED** [review]

**Comment by Infra-Red** [comment]
Thanks for the contribution @hjaffan !

**Pull request merged**
