### PR TITLE
Adding Content-Type headers for JSON

### PR DESCRIPTION
**Pull request by rogeruiz**
Since updating to ES 6.0 means that endpoints will require strict content type checking, I'm adding these headers so that the `curl` commands are successful. 

:eyes: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

### CODE REVIEW

**Comment by rogeruiz** [comment]
Related to the changes here, 18F/cg-deploy-logsearch#143

**Comment by axelaris** [comment]
Hi @rogeruiz ,
sorry for not looking into this issue for a long time.
We just upgraded Elastic stack to v6. Could you please check if the issue is still actual?
If so - could you please do rebase.
Thanks.

**Comment by vetin4ri** [comment]
Yes, the issue still persists. Do you need a new pull request for that @axelaris?

**Comment by axelaris** [comment]
Hi @vetin4ri,
thats would be nice ;-)

**Comment by axelaris** [comment]
Closed in favor of #137

**Pull request closed without merging**
