### PR TITLE
Upgrade to ES6

### PR DESCRIPTION
**Pull request by timothy-spencer**
This is a set of changes that worked for us to get ES6 going.  The biggest issues that I found were:
1) Document types.  These went away in ES6, so the index mappings and a lot of other things had to be rejiggered to handle this.
2) String type.  These also went away, so they needed to be rewritten to be text and keyword types.
3) Commandline and config options.  Some changed and had to be redone in different ways or removed.
4) Kibana bulk import of dashboards/etc.  This was largely undocumented, so I had to kind of reverse engineer this by doing a lot of staring at .kibana queries.
5) Migration-related things (update .kibana index and logstash queue).

It definitely is not perfect, but it is a step in the right direction, and it works, so maybe you would be able to crib from this when you are able to do a more comprehensive upgrade.  Here are the caveats that you should be aware of:
1) There is still a lot of document type related code floating around.  None of it seems to affect what we are doing, but it worries me, because it creates the potential for landmines.  I just changed what was needed to get it going.
2) I did not adjust documentation at all.  Again, just got it working.
3) I did work in https://github.com/18F/logsearch-for-cloudfoundry/pull/14 at the same time, so if they can be used standalone at all, they may not actually stand on their own at all because I never tried that out.
4) I just noticed that we have some changes from some other PRs in here too (https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/121, for example).

### CODE REVIEW

**Comment by axelaris** [comment]
Hi guys,
thank you for contribution!
As I can see - you've dropped `syslog_forwarder` job temporarily. What was the reason and what _temporarily_ means there?
@timothy-spencer @jmcarp

**Comment by timothy-spencer** [comment]
@axelaris Apologies!  Your request for information on the syslog_forwarder job got lost in my inbox somehow.  I am not actually sure why that got turned off.  @jmcarp would probably be better able to answer that.

**Comment by axelaris** [comment]
Hi @jmcarp,
any update on `syslog_forwarder` job?

**Comment by axelaris** [comment]
Hi @timothy-spencer @jmcarp ,
thank you again for your contribution, and sorry for not getting back to you so long.
I'm working on upgrade ES to v6, but I do not want to merge this PR as-is, because it contains a lot of code not directly related to upgrade itself. 
Instead of that, I created a separate PR #128, and going to cherry-pick only appropriate commits there.
I believe it will be faster than rebasing this PR. Thank you for understanding.

**Comment by axelaris** [comment]
Closed in favor of #128

**Pull request closed without merging**
