### PR TITLE
Add archiver syslog job.

### PR DESCRIPTION
**Pull request by jmcarp**
Adds an archiver logstash job that reads off syslog and writes to user-defined outputs with minimal filtering. Our use case is to consume the firehose and write it directly to s3 without any filtering using the s3 output plugin. We used to do this with the ingestor job, but now that filtering has moved from the parsers to the ingestors, we need another method for getting unfiltered logs to s3.

cc @LinuxBozo @cnelson

### CODE REVIEW

**Comment by jmcarp** [comment]
By the way, the existing archiver jobs look like they haven't been updated for a few years, and I'm not sure why I'd use them to manually upload to s3 instead of using the s3 output plugin with the archiver I'm proposing here. What do you think about dropping the existing archiver jobs @Infra-Red ?

**Comment by Infra-Red** [comment]
@jmcarp I'm just wondering why you remove `syslog_forwarder` job from release?

**Comment by jmcarp** [comment]
Sorry @Infra-Red, I pushed some unrelated commits to this branch. I just reverted them.

**Comment by Infra-Red** [comment]
@jmcarp Overall looks good, but could you add some additional property to provide rules in filter block. I think it maybe useful to have ability to provide some additional configuration. Smth similar to `content` property from the following PR https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/91 will be enough. Thanks!

**Comment by sarneaud** [comment]
We've been experimenting with this archiver (thanks!).  We'd like to submit some improvements once this PR is merged.

**Comment by jmcarp** [comment]
Updated. WDYT @Infra-Red @sarneaud ?

**Comment by sarneaud** [comment]
We don't need the filtering because we have the same use case as you.  I guess that's LGTM :)

We're currently debugging some Logstash stability issues in our environment.  Hopefully we'll have some PRs soon to make things more robust.

**Comment by jmcarp** [comment]
We don't need the filters either. @Infra-Red did you have a specific use case for them? If not, I can revert the last commit to keep this simple.

Looking forward to your improvements @sarneaud !

**Comment by Infra-Red** [comment]
I'd like to keep filters options, currently I don't have some specific use cases for filters, but I think it maybe helpful to remove smth like secrets from archived logs.

**Review by Infra-Red — APPROVED** [review]

**Pull request merged**
